### DISCUSSION TITLE
Improve the NUKE build even more

### DISCUSSION THREAD

**Discussion by ITaluone** [fluentassertions/fluentassertions#2094] [Ideas]
Hi

After a few improvements on the NUKE build, I have found following neat little thing: Generating the yml file(s) 

E.g. if you decorate your `Build` class with the following:

```csharp
[GitHubActions(
    name: "build-ci",
    GitHubActionsImage.WindowsLatest,
    InvokedTargets = new[] { nameof(Push) },
    On = new[]
    {
        GitHubActionsTrigger.Push,
        GitHubActionsTrigger.PullRequest
    },
    ImportSecrets = new [] { nameof(ApiKey) },
    FetchDepth = 0)]
    class Build : NukeBuild
    {
        ...
    }
```
it will generate the following yaml file: `.github/workflows/buil-ci.yml` with following content

```yml
name: build-ci

on: [push, pull_request]

jobs:
  windows-latest:
    name: windows-latest
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v3
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}
      - name: Run './build.cmd Push'
        run: ./build.cmd Push
        env:
          ApiKey: ${{ secrets.API_KEY }}
      - uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: Artifacts
```

### Pros
- You don't have to care about yaml in anyway
- Never have to deal with indentation errors in future

### (Possible) Draw-Backs
- It will generate one job per `GithubActionImage`
- It will (at time of writing) does not support having multiple (different) generates jobs per file. e.g. the `only-unit-tests` job will be in a seperate file
- We either have to rename the parameter `ApiKey` to `Nugetapikey` in the build file or the github secret to `API_KEY`

Let me know if this change is wanted :) I am happy to contribute this

Besides this change I would:
- Move the coveralls step to NUKE
- Do not care about setting up .NET (since NUKE does this already by itself, if no SDK is installed/found)
- Using the `GitHubActions` injection to retrieve several variables and retire several parameters
